"""empty message

Revision ID: 7259d28bb8e2
Revises: 7e29003ebf89
Create Date: 2026-02-28 21:50:02.003042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7259d28bb8e2'
down_revision = '7e29003ebf89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nspresupuestosvalidaciones',
    sa.Column('ir', sa.Integer(), nullable=False),
    sa.Column('numvalidacion', sa.Integer(), nullable=False),
    sa.Column('idempresa', sa.String(length=25), nullable=True),
    sa.Column('tipodocumento', sa.String(length=25), nullable=True),
    sa.Column('numdocumento', sa.String(length=50), nullable=True),
    sa.Column('numlinea', sa.Integer(), nullable=True),
    sa.Column('variable', sa.String(length=50), nullable=True),
    sa.Column('errordescripcion', sa.Text(), nullable=True),
    sa.Column('error', sa.Integer(), nullable=True),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ir', 'numvalidacion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nspresupuestosvalidaciones')
    # ### end Alembic commands ###
