"""Añadir tablas de presupuestos

Revision ID: 7e29003ebf89
Revises: c0c582ef79f4
Create Date: 2026-02-27 23:38:25.523889

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e29003ebf89'
down_revision = 'c0c582ef79f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nspresupuestos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session', sa.String(length=25), nullable=True),
    sa.Column('idempresa', sa.String(length=25), nullable=True),
    sa.Column('tipodocumento', sa.String(length=25), nullable=True),
    sa.Column('numdocumento', sa.String(length=50), nullable=True),
    sa.Column('fechadocumento', sa.String(length=10), nullable=True),
    sa.Column('fechavalidez', sa.String(length=10), nullable=True),
    sa.Column('emisor', sa.String(length=255), nullable=True),
    sa.Column('naturaleza', sa.String(length=15), nullable=True),
    sa.Column('numpedidocliente', sa.String(length=50), nullable=True),
    sa.Column('numpedidoproveedor', sa.String(length=50), nullable=True),
    sa.Column('cifemisor', sa.String(length=25), nullable=True),
    sa.Column('estado', sa.Integer(), nullable=True),
    sa.Column('codigoproveedorbc', sa.String(length=50), nullable=True),
    sa.Column('codigoproyectobc', sa.String(length=50), nullable=True),
    sa.Column('numalbaran', sa.String(length=50), nullable=True),
    sa.Column('importebruto', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('importeiva', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('importeneto', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('porcentajeiva', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('pdf', sa.LargeBinary(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('hash', sa.String(length=32), nullable=True),
    sa.Column('tiempoproceso', sa.Integer(), nullable=True),
    sa.Column('tokensentrada', sa.Integer(), nullable=True),
    sa.Column('tokenssalida', sa.Integer(), nullable=True),
    sa.Column('tokensinterno', sa.Integer(), nullable=True),
    sa.Column('tokenstotal', sa.Integer(), nullable=True),
    sa.Column('usuariocreacion', sa.String(length=25), nullable=True),
    sa.Column('auditcreacion', sa.String(length=19), nullable=True),
    sa.Column('usuariomodificacion', sa.String(length=25), nullable=True),
    sa.Column('auditmodificacion', sa.String(length=19), nullable=True),
    sa.Column('search', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nspresupuestoslineas',
    sa.Column('ir', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idempresa', sa.String(length=25), nullable=True),
    sa.Column('tipodocumento', sa.String(length=25), nullable=True),
    sa.Column('numdocumento', sa.String(length=50), nullable=True),
    sa.Column('numlinea', sa.Integer(), nullable=True),
    sa.Column('articulobc', sa.String(length=50), nullable=True),
    sa.Column('codigoproyectobc_line', sa.String(length=50), nullable=True),
    sa.Column('naturaleza', sa.String(length=10), nullable=True),
    sa.Column('referencia', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('unidades', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('preciounitario', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('preciototal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('descuento', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('procesado', sa.Boolean(), nullable=True),
    sa.Column('usuariocreacion', sa.String(length=25), nullable=True),
    sa.Column('auditcreacion', sa.String(length=19), nullable=True),
    sa.Column('usuariomodificacion', sa.String(length=25), nullable=True),
    sa.Column('auditmodificacion', sa.String(length=19), nullable=True),
    sa.Column('search', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('ir')
    )
    op.drop_table('document_line')
    op.drop_table('document')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('doc_type', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('filename', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('supplier_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('doc_date', mysql.DATETIME(), nullable=True),
    sa.Column('total_base', mysql.FLOAT(), nullable=True),
    sa.Column('total_tax', mysql.FLOAT(), nullable=True),
    sa.Column('total_amount', mysql.FLOAT(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('document_line',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('document_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('quantity', mysql.FLOAT(), nullable=True),
    sa.Column('price_unit', mysql.FLOAT(), nullable=True),
    sa.Column('tax_rate', mysql.FLOAT(), nullable=True),
    sa.Column('total_line', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('document_line_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('nspresupuestoslineas')
    op.drop_table('nspresupuestos')
    # ### end Alembic commands ###
