"""Modelo profesional con herencia

Revision ID: cb8ab1589fd8
Revises: 
Create Date: 2026-02-28 22:38:52.044727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb8ab1589fd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nsdocumentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('discriminator', sa.String(length=20), nullable=True),
    sa.Column('idempresa', sa.String(length=25), nullable=True),
    sa.Column('numdocumento', sa.String(length=50), nullable=True),
    sa.Column('fechadocumento', sa.String(length=10), nullable=True),
    sa.Column('emisor', sa.String(length=255), nullable=True),
    sa.Column('cifemisor', sa.String(length=25), nullable=True),
    sa.Column('importebruto', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('importeiva', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('importeneto', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('usuariocreacion', sa.String(length=25), nullable=True),
    sa.Column('auditcreacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nsusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('nsalbaranes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_pedido_erp', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['nsdocumentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nsdocumentos_lineas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=True),
    sa.Column('numlinea', sa.Integer(), nullable=True),
    sa.Column('referencia', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('unidades', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('preciounitario', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('preciototal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['documento_id'], ['nsdocumentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nsdocumentos_validaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=True),
    sa.Column('numlinea', sa.Integer(), nullable=True),
    sa.Column('variable', sa.String(length=50), nullable=True),
    sa.Column('errordescripcion', sa.Text(), nullable=True),
    sa.Column('error', sa.Integer(), nullable=True),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['documento_id'], ['nsdocumentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nspresupuestos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fechavalidez', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['nsdocumentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nspresupuestos')
    op.drop_table('nsdocumentos_validaciones')
    op.drop_table('nsdocumentos_lineas')
    op.drop_table('nsalbaranes')
    op.drop_table('nsusers')
    op.drop_table('nsdocumentos')
    # ### end Alembic commands ###
